### ISSUE TITLE
[BUG] cocogitto-bot not honoring the `ignore_merge_commits` configuration

### ISSUE THREAD

**Issue by luciidlou** [cocogitto/cocogitto-bot#15]
**Describe the bug**
The cocogitto bot is not ignoring commit messages that follow the `Merge branch 'main' into <some-branch-name>` pattern. This is typically the commit message pattern that gets automatically produced when using GitHub's `Update Branch` button in the UI.

**To Reproduce**
1. Create new branch off of `main`. 
2. Push any change up on your new branch and open a PR. 
3. Update `main` with a change. 
4. Select `Update Branch` on your PR in the GItHub UI (this syncs your working branch with `main`).
5. Cocogitto bot should yell about the commit message that gets automatically created.

**Expected behavior**
The bot is expected to ignore the commit message described above.

**Additional context**
The repo _does_ have a `cog.toml` with the `ignore_merge_commits = true` configured. I've also attached some screenshots to add further context. The repo is private, so it cannot be linked.
![Screen Shot 2023-08-07 at 2 42 53 PM](https://github.com/cocogitto/cocogitto-bot/assets/87360583/425b6a7b-cd0d-4566-9b55-2f7aefad6b57)
![Screen Shot 2023-08-07 at 2 42 41 PM](https://github.com/cocogitto/cocogitto-bot/assets/87360583/f227e18d-241b-4187-bcf1-5fd06f871292)

**Comment by the-wondersmith** [comment]
@oknozor in the spirit of full disclosure @luciidlou and I coworkers and the private repo he's referencing is one of ours.

@luciidlou I 100% spoke incorrectly when I was explaining and said that the default behavior of the bot was to ignore merge commits - that _was_ the default behavior prior to the recently PR that replaced `conventional_commit_parser` with `cocogitto` directly. The [default](https://github.com/cocogitto/cocogitto/blob/main/src/settings/mod.rs#L55) `cocogitto` configuration is to _not_ ignore merge commits and if there is no `cog.toml` in the target repo, the bot [will now](https://github.com/cocogitto/cocogitto-bot/blob/main/src/main.rs#L94) use the default for `Settings`.


@oknozor should I put up another PR to change the bot's config creation to something like:

```rust
// Parse the config file into Cocogitto `Settings` (falling
// back to the default if the target repo doesn't have a `cog.toml`)
let cog_config = Settings::try_from(cog_file).unwrap_or_else(|_| Settings {
    ignore_merge_commits: true,
    ..Settings::default()
});
```

??

**Comment by the-wondersmith** [comment]
@oknozor Actually... [this](https://github.com/cocogitto/cocogitto-bot/blob/main/src/main.rs#L84) might be an issue too. That should probably be either the repo-specific "main", the branch the PR is being merged into, _or_ the branch that's being merged _from_. Not actually sure which without some more thought...

**Comment by the-wondersmith** [comment]
@oknozor [PR](https://github.com/cocogitto/cocogitto-bot/pull/16) is up

I was able to verify proper parsing behavior of committed `cog.toml` files as well, so I _think_ that should fix the actual code issue(s)? I'm gonna have to lean on your expertise for whether or not anything else might be amiss to cause the observed behavior.

There's no chance it's something like "existing repos need to re-auth the bot to get the updated version" or something, is there?

**Comment by the-wondersmith** [comment]
@oknozor Bump

**Comment by the-wondersmith** [comment]
@luciidlou The [fix PR](https://github.com/cocogitto/cocogitto-bot/pull/16) for this looks to be merged. Would you be so kind as to verify that it now works as expected?

**Comment by luciidlou** [comment]
@oknozor Hey there! The PR @the-wondersmith linked above looks like it was merged, but we are still seeing the same issue today (see screenshot). Do we need to remove and re-add cocogitto-bot to any existing repos in order for the changes to take place? Or is there some central deployment that needs updating? Or does the PR that was merged simply just not solve the problem?
![Screenshot 2023-08-23 at 1 42 19 PM](https://github.com/cocogitto/cocogitto-bot/assets/87360583/6411f95e-79e7-4a1f-92cc-915d2b3f7688)

**Comment by oknozor** [comment]
Hey, I am not home right now and I don't have access to the cluster where the bot is deployed. I will check the deployment next week.

**Comment by luciidlou** [comment]
@oknozor bump

**Comment by the-wondersmith** [comment]
@oknozor bumping again

**Comment by oknozor** [comment]
Hey, this should be working, can you close/reopen your pull request. 
I am not able to reproduce this behavior (see: https://github.com/cocogitto/cocogitto_bot_playground/pull/18).

If this is still an issue can you provide a simple reproducer on a public repository ?
